FROM ubuntu:18.04
#Dependiendo de la versión de ubuntu que pongaos se descarga un versión distinta de git

RUN apt-get update
RUN apt-get install -y git

#RUN git --version
#Poniendo CMD al hacer el run imprime la versión de git
CMD git --version 